# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dbac033971e1cc79b7b2a30cbc3d533e9d8e9ea3667d09a2ce20c59f68eab89350f37de1b8baa6d4c6d8934735ac3f80ea854233557ad86fb5bd04fa438f020

test:
  secret_key_base: 5fbbd927cba47a90d3102fe3ad363f7651a928424655abc906f1e4fa454c69b6ff835a015c91cb9ac535636802c4d8ee49e2d450b2bf219360752f0b90b5b0db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
